---
title: "Reset to 2019-04 RNASeq Analysis Parameters"
author: "Trevor Randall"
date: "25/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)
install_version("foreach", version = "1.4.4")
install_version("bit64", version = "0.9-7")
install_version("splines", version = "3.5.1")
install_version("Formula", version = "1.2-3")
install_version("assertthat", version = "0.2.0")
install_version("mixsqp", version = "0.1-97")
install_version("latticeExtra", version = "0.6-28")
install_version("blob", version = "1.1.1")
#install_version("GenomeInfoDbData", version = "1.1.0") #From Bioconductor
install_version("yaml", version = "2.2.0")
install_version("numDeriv", version = "2016.8-1")
install_version("pillar", version = "1.3.1")
install_version("RSQLite", version = "2.1.1")
install_version("backports", version = "1.1.3")
install_version("lattice", version = "0.20-38")
install_version("bbmle", version = "1.0.20")
install_version("digest", version = "0.6.18")
install_version("RColorBrewer", version = "1.1-2")
#install_version("XVector", version = "0.20.0") #From Bioconductor?
install_version("checkmate", version = "1.9.1")
#install_version("htmltoolscolorspace", version = "1.4-0") #From Bioconductor?
install_version("htmltools", version = "0.3.6")
install_version("Matrix", version = "1.2-16")
install_version("plyr", version = "1.8.4")
install_version("XML", version = "3.98-1.19")
install_version("pkgconfig", version = "2.0.2")
install_version("emdbook", version = "1.3.11")
#install_version("genefilter", version = "1.62.0") #From Bioconductor?
#install_version("zlibbioc", version = "1.26.0")#From Bioconductor?
install_version("xtable", version = "1.8-3")
install_version("scales", version = "1.0.0")
#install_version("apeglm", version = "1.2.1")#From Bioconductor?
install_version("htmlTable", version = "1.13.1")
install_version("tibble", version = "2.1.1")
#install_version("annotate", version = "1.58.0")#From Bioconductor?
install_version("ggplot2", version = "3.1.0")
install_version("ashr", version = "2.2-32")
install_version("nnet", version = "7.3-12")
install_version("lazyeval", version = "0.2.2")
install_version("survival", version = "2.43-3")
install_version("magrittr", version = "1.5")
install_version("crayon", version = "1.3.4")



install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
install_version("", version = "")
```

