---
title: "CF39 25_vs_OtherTemps"
author: "Trevor Randall"
date: "30/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Clear Global Environment
```{r}
remove(list = ls())
```


```{r}
#Set Library Directory
#PC Path
.libPaths(c("L:/RStudios/RPackRatLibLocations", "L:/RStudios/RPackRat_2019_04_DESEQLibs"))

#Set working directory
#PC Path
setwd("E:/Dropbox/Dropbox/Harrison Lab - Trevor Randall/RNASeq Analysis/RNASeqAnlyPkrat_2020_03/Analysis Temp X vs X/Secondary Analyses/CF39 25_vs_OtherTemps")
#Laptop Path
#Set Library Directory
#.libPaths(c(""))
#setwd("")
```

Libraries to open:
```{r}
library(readr)
library(VennDiagram)
```


#Open Wanted files for analysis
```{r}
CF39_25vs29_TDESEQ <- read_delim("../../25vs29/CF39_25vs29_TDESEQ.txt", "\t", escape_double = FALSE, trim_ws = TRUE)

CF39_25vs33_TDESEQ <- read_delim("../../25vs33/CF39_25vs33_TDESEQ.txt", "\t", escape_double = FALSE, trim_ws = TRUE)

CF39_25vs37_TDESEQ <- read_delim("../../25vs37/CF39_25vs37_TDESEQ.txt", "\t", escape_double = FALSE, trim_ws = TRUE)

CF39_25vs41_TDESEQ <- read_delim("../../25vs41/CF39_25vs41_TDESEQ.txt", "\t", escape_double = FALSE, trim_ws = TRUE)
```

#Remove Unwanted Columns
```{r}
ColToRemove <- c("baseMean", "lfcSE", "stat", "pvalue", "gene", "product", "locusNumber")

TDESEQList_25vs29_Shrunk <- CF39_25vs29_TDESEQ[, !names(CF39_25vs29_TDESEQ) %in% ColToRemove, drop = F]
colnames(TDESEQList_25vs29_Shrunk) <- c("locus", "CF39 Log2FoldChange_25vs29",  "CF39 padj_25vs29")

TDESEQList_25vs33_Shrunk <- CF39_25vs33_TDESEQ[, !names(CF39_25vs33_TDESEQ) %in% ColToRemove, drop = F]
colnames(TDESEQList_25vs33_Shrunk) <- c("locus", "CF39 Log2FoldChange_25vs33",  "CF39 padj_25vs33")

TDESEQList_25vs37_Shrunk <- CF39_25vs37_TDESEQ[, !names(CF39_25vs37_TDESEQ) %in% ColToRemove, drop = F]
colnames(TDESEQList_25vs37_Shrunk) <- c("locus", "CF39 Log2FoldChange_25vs37",  "CF39 padj_25vs37")

TDESEQList_25vs41_Shrunk <- CF39_25vs41_TDESEQ[, !names(CF39_25vs41_TDESEQ) %in% ColToRemove, drop = F]
colnames(TDESEQList_25vs41_Shrunk) <- c("locus", "CF39 Log2FoldChange_25vs41",  "CF39 padj_25vs41")
```

#Combine shrunk files
```{r}
LocusGeneAssociation <- read_csv("../../Locus_GeneNamesAndPredictedFunction.csv")

Combined_List_Shrunk <- 0
Combined_List_Shrunk <- merge(TDESEQList_25vs29_Shrunk, y = TDESEQList_25vs33_Shrunk, by.x= "locus", by.y = "locus", all.x = T, all.y = T)
Combined_List_Shrunk <- merge(Combined_List_Shrunk, y = TDESEQList_25vs37_Shrunk, by.x= "locus", by.y = "locus", all.x = T, all.y = T)
Combined_List_Shrunk <- merge(Combined_List_Shrunk, y = TDESEQList_25vs41_Shrunk, by.x= "locus", by.y = "locus", all.x = T, all.y = T)
Combined_List_Shrunk <- merge(Combined_List_Shrunk, LocusGeneAssociation, by = "locus")

write.table(x = Combined_List_Shrunk, file="./Combined List 25vsOtherTemps Analysis Shrunk.txt", sep="\t", row.names=FALSE, col.names=colnames(Combined_List_Shrunk), quote=F)
```

#Remove igtop/igbot from analysis
#Remove Unwanted Columns
```{r}
ColToRemove <- c("baseMean", "lfcSE", "stat", "pvalue", "gene", "product", "locusNumber")

TDESEQList_25vs29_Shrunk2_Full <- CF39_25vs29_TDESEQ[, !names(CF39_25vs29_TDESEQ) %in% ColToRemove, drop = F]
TDESEQList_25vs29_Shrunk2TailListSense <- TDESEQList_25vs29_Shrunk2_Full[((grep((glob2rx('*_sense')), TDESEQList_25vs29_Shrunk2_Full$locus))), ]
TDESEQList_25vs29_Shrunk2TailListAntiSense <- TDESEQList_25vs29_Shrunk2_Full[((grep((glob2rx('*_antis')), TDESEQList_25vs29_Shrunk2_Full$locus))), ]
TDESEQList_25vs29_Shrunk2TailListMerged <- rbind(TDESEQList_25vs29_Shrunk2TailListSense, TDESEQList_25vs29_Shrunk2TailListAntiSense)
TDESEQList_25vs29_Shrunk2 <- TDESEQList_25vs29_Shrunk2TailListMerged[order(TDESEQList_25vs29_Shrunk2TailListMerged$locus), ]
colnames(TDESEQList_25vs29_Shrunk2) <- c("locus", "CF39 Log2FoldChange_25vs29",  "CF39 padj_25vs29")



TDESEQList_25vs33_Shrunk2_Full <- CF39_25vs33_TDESEQ[, !names(CF39_25vs33_TDESEQ) %in% ColToRemove, drop = F]
TDESEQList_25vs33_Shrunk2TailListSense <- TDESEQList_25vs33_Shrunk2_Full[((grep((glob2rx('*_sense')), TDESEQList_25vs33_Shrunk2_Full$locus))), ]
TDESEQList_25vs33_Shrunk2TailListAntiSense <- TDESEQList_25vs33_Shrunk2_Full[((grep((glob2rx('*_antis')), TDESEQList_25vs33_Shrunk2_Full$locus))), ]
TDESEQList_25vs33_Shrunk2TailListMerged <- rbind(TDESEQList_25vs33_Shrunk2TailListSense, TDESEQList_25vs33_Shrunk2TailListAntiSense)
TDESEQList_25vs33_Shrunk2 <- TDESEQList_25vs33_Shrunk2TailListMerged[order(TDESEQList_25vs33_Shrunk2TailListMerged$locus), ]
colnames(TDESEQList_25vs33_Shrunk2) <- c("locus", "CF39 Log2FoldChange_25vs33",  "CF39 padj_25vs33")

TDESEQList_25vs37_Shrunk2_Full <- CF39_25vs37_TDESEQ[, !names(CF39_25vs37_TDESEQ) %in% ColToRemove, drop = F]
TDESEQList_25vs37_Shrunk2TailListSense <- TDESEQList_25vs37_Shrunk2_Full[((grep((glob2rx('*_sense')), TDESEQList_25vs37_Shrunk2_Full$locus))), ]
TDESEQList_25vs37_Shrunk2TailListAntiSense <- TDESEQList_25vs37_Shrunk2_Full[((grep((glob2rx('*_antis')), TDESEQList_25vs37_Shrunk2_Full$locus))), ]
TDESEQList_25vs37_Shrunk2TailListMerged <- rbind(TDESEQList_25vs37_Shrunk2TailListSense, TDESEQList_25vs37_Shrunk2TailListAntiSense)
TDESEQList_25vs37_Shrunk2 <- TDESEQList_25vs37_Shrunk2TailListMerged[order(TDESEQList_25vs37_Shrunk2TailListMerged$locus), ]
colnames(TDESEQList_25vs37_Shrunk2) <- c("locus", "CF39 Log2FoldChange_25vs37",  "CF39 padj_25vs37")

TDESEQList_25vs41_Shrunk2_Full <- CF39_25vs41_TDESEQ[, !names(CF39_25vs41_TDESEQ) %in% ColToRemove, drop = F]
TDESEQList_25vs41_Shrunk2TailListSense <- TDESEQList_25vs41_Shrunk2_Full[((grep((glob2rx('*_sense')), TDESEQList_25vs41_Shrunk2_Full$locus))), ]
TDESEQList_25vs41_Shrunk2TailListAntiSense <- TDESEQList_25vs41_Shrunk2_Full[((grep((glob2rx('*_antis')), TDESEQList_25vs41_Shrunk2_Full$locus))), ]
TDESEQList_25vs41_Shrunk2TailListMerged <- rbind(TDESEQList_25vs41_Shrunk2TailListSense, TDESEQList_25vs41_Shrunk2TailListAntiSense)
TDESEQList_25vs41_Shrunk2 <- TDESEQList_25vs41_Shrunk2TailListMerged[order(TDESEQList_25vs41_Shrunk2TailListMerged$locus), ]
colnames(TDESEQList_25vs41_Shrunk2) <- c("locus", "CF39 Log2FoldChange_25vs41",  "CF39 padj_25vs41")
```


#Combine shrunk files
```{r}
LocusGeneAssociation <- read_csv("../../Locus_GeneNamesAndPredictedFunction.csv")

Combined_List_Shrunk2 <- 0
Combined_List_Shrunk2 <- merge(TDESEQList_25vs29_Shrunk2, y = TDESEQList_25vs33_Shrunk2, by.x= "locus", by.y = "locus", all.x = T, all.y = T)
Combined_List_Shrunk2 <- merge(Combined_List_Shrunk2, y = TDESEQList_25vs37_Shrunk2, by.x= "locus", by.y = "locus", all.x = T, all.y = T)
Combined_List_Shrunk2 <- merge(Combined_List_Shrunk2, y = TDESEQList_25vs41_Shrunk2, by.x= "locus", by.y = "locus", all.x = T, all.y = T)
Combined_List_Shrunk2 <- merge(Combined_List_Shrunk2, LocusGeneAssociation, by = "locus")

write.table(x = Combined_List_Shrunk2, file="./Combined List 25vsOtherTemps Analysis Shrunk2.txt", sep="\t", row.names=FALSE, col.names=colnames(Combined_List_Shrunk2), quote=F)
```