---
title: "VolcanoPlot Analysis Pure Temp Analysis"
author: "Trevor Randall"
date: "07/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Clear Global Environment
```{r}
remove(list = ls())
```


Libraries to install:
```{r, eval=FALSE}
install.packages('VennDiagram')
```


Libraries to open:
```{r}
library(readr)
library(ggplot2)
library(EnhancedVolcano)
```


```{r}
#Set Library Directory
#PC Path
.libPaths(c("L:/RStudios/RPackRatLibLocations", "L:/RStudios/RPackRat_2019_04_DESEQLibs"))

#Set working directory
#PC Path
setwd("E:/Dropbox/Dropbox/Harrison Lab - Trevor Randall/RNASeq Analysis/RNASeqAnlyPkrat_2020_03/CF39vsCF39S/Pure Temperature Analysis Comparisons/")
#Laptop Path
#Set Library Directory
#.libPaths(c(""))
#setwd("")
#sink(file = "./RSessionRawRun.txt") 
```

#Opening Preprocessed Datasets
```{r}
LCFShrinkResults_apeglm <- read_delim("../25 vs 25/My DESEQ Script/DESeq_results_LCFShrinkResults-apeglm.txt", "\t", escape_double = FALSE, trim_ws = TRUE)

#rownames(LCFShrinkResults_apeglm)<- LCFShrinkResults_apeglm[,1]
#LCFShrinkResults_apeglm <- LCFShrinkResults_apeglm[,-1]

LCFShrinkResults_normal <- read_delim("../25 vs 25/My DESEQ Script/DESeq_results_LCFShrinkResults-normal.txt", "\t", escape_double = FALSE, trim_ws = TRUE)

LCFShrinkResults_ashr <- read_delim("../25 vs 25/My DESEQ Script/DESeq_results_LCFShrinkResults-ashr.txt", "\t", escape_double = FALSE, trim_ws = TRUE)
```

#Creating Vocano Plots for apeglm dataset
```{r}
EnhancedVolcano(LCFShrinkResults_apeglm, #TODO Can I use Padj instead of Pvalue?
                lab = LCFShrinkResults_apeglm$locus, #TODO Do I want to do a prior screen to eliminate the majority of the non reg genes?
                x = 'log2FoldChange',
                y = 'pvalue',
                xlim = c(-5, 8)) #TODO Can I change/adj the legend? Also, what are the lables?
```


